# Generated by Django 5.0.6 on 2024-08-08 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackres',
            name='sub_id',
        ),
    ]
