# Generated by Django 5.0.6 on 2024-09-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('staff_id', models.CharField(max_length=20)),
                ('subjects', models.ManyToManyField(related_name='staff_handling', to='Home.subject_detail')),
            ],
        ),
    ]
