# Generated by Django 5.0.6 on 2024-09-23 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackres',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Home.staff'),
        ),
    ]
